
RAID = [
    "siapa, yang mengaku raja, tunjukkan kau punya muka",
    "magnum isi peluru rima, siap hantam kau punya nyawa",
    "tak terlihat mata, namun terdengar ditelinga, meracuni kau punya kepala, robek kau punya sendi lidah, microphonemu kubuat PATAH",
    "terbit dari timur, tinggi tak terjamah, menjulang tinggi bagai gunung HIMALAYA, kubuat kau tenggelam dibarat, terkubur jauh didalam menyentuh gelapnya bawah tanah",
    "Aku goliath selatan, kau tak suka mari buktikan",
    "i'm the FASTEST GUN IN THE SOUTH, Skema perang 65 70 langsung kujalankan",
    "(BANG BANG BANG) rasakan tembakan ini menembus kau punya tinggi hati",
    "teknik tak terdeteksi, sulit dimengerti bagai kitab suci",
    "aku original, dengan sentuhan magic harmoni",
    "aku bagai horus bersembunyi mengawasi bagai mata ILLUMINATI",
    "Silahkan hargai kepalaku karena dirimu takkan mampu, panggil pasukanmu serang aku lancarkan diseluruh penjuru",
    "pakailah amunisimu, bidiklah tiap langkahku",
    "kusiap INJAK julukanmu, sampai jumpa di arena panas bersamaku",
    "tanpa senapan di pinggang usir singa yang singgah",
    "sekarang mereka segan dahulu pandang rendah",
    "tanpa senapan di pinggang usir singa yang singgah",
    "aku melaju kencang saat target kupasang",
    "we goin BANG...BANG ",
    "(you better watchout coz now we BANG..BANG)",
    "(laughin so loud on my way to the BANK..BANK)",
    "(you better watchout coz now we BANG..BANG)",
    "Sisir kota orang maca ada rambut",
    "bangun istana diatas lapak lapuk",
    "ada yang sambit ada yang hendak sambut",
    "mereka tak dipuncak tapi kalang kabut",
    "diincar timah panas karena tim aku panas",
    "aku senyum ramah tapi rima ganas, siapa kau boy?",
    "dari selatan jakarta ke wild wild west..cowboy",
    "buka majalah aku cek horoskop, mereka bilang kubintang aku butuh teleskop",
    "aku icon baru coba cek di desktop, anak kemarin sore raja pagi besok",
    "bisnis ku handle, pernah tolak label",
    "mereka cap aku bodoh itu salah stempel",
    "kini saatku untuk unjukkan taring",
    "hustle cari laba semoga beda jaring",
    "tiap kurekaman ada PEMAKAMAN",
    "i kill wack rappers itu PEMAHAMAN",
    "nikahi permainan aku ikrar di altar",
    "bahkan kendrick? HANYA LAMAR",
    "musuh komentar, nyalakan api, kepala dingin TANPA ES DI TOPI",
    "aku diam mereka senang rumpi, lirikku peluru mereka PASANG ROMPI",
    "pada ketinggian kita rasa takut, diatas ada banyak penghasut",
    "dekati kita dengan lain maksud, karena para parasit butuhkan parasut",
    "angka angka tidak buatku angku, realita buat jatuh dari bangku",
    "sekarang hanya ada dua pilihanmu, lari dariku atau LARI DENGANKU",
    "kubangkitkan neraka karena akulah rajanya",
    "trap this, and trap that, kubuat mereka terjebak",
    "tak perlu sertifikasi diri, cukuplah karya sebagai bukti",
    "persetan mereka berkata 'SELATAN TANPA SKILL' kini kuunjuk gigi",
    "Musikku DOWNTEMPO, ku tak takut dengan HIGH TEMPO",
    "lirikku bukan BRONX, kau bilang terbelakang tapi bukan NDESO",
    "kujaga sebutan KEEP IT TRILL, lirik bening aku KEEP IT REAL",
    "Naikkan bendera keujung langit untuk kau sembah sebut aku KING OF KILL",
    "Silahkan menjiplak gayaku, karena kau takut akulah di kasta nomor SATU",
    "teruslah menyebut kecepatanmu itu dapat menumbangkan mahkota berkilau dikepalaku",
    "bila mampu, kejar TOP SPEED ku dengan mesin andalanmu",
    "Shut me down..cobalah SEBELUM SENJA menjemputmu",
    "Call me BIG VICTORY, all i do is win, represent RUN BDG",
    "bangin in the east, bangin in the west",
    "Street to club, we the BEST",
    "you left behind, we first place",
    "they to slow cuz i'm movin FAST",
    "lagi lagi si haus perhatian minta balasan jalan pintas ngetop dengan cari cari alasan",
    "bau menyengat ketenaran sedang di incar maksa ngejar mirip si konak yang lagi butuh pacar",
    "lest zi black versus 8 ball profsesional bagai bandingkan bebek sawah melawan donal",
    "gapapa, ku bantu kau terkenal sekarang jarang jarang ku baik pada lawan yang menyerang",
    "perang tak berparang tak pula bersangkur kau cuma bulu ketek yang ilang sekali dicukur",
    "omelan mirip dengkur pas tidur gak nyadar face to face battle on d stage baby, so pasti modar",
    "diss mentoknya fisik biar bodohmu tertutupi perutku makin gendut asupan gizi tercukupi",
    "ngerap masih rapi gak berantakan lagi  you inget kalo kalah titit di potong ojo melayu",
    "saat nanti ku menang, jangan kau sembunyi ingat titit dipotong, jangan kau lari",
    "bermain aman dari jauh mulutmu berak jaminan mutu dari dekat pasti jaga jarak",
    "perlu di garis bawahi lirik mu bilang 'semua' Gue solo mc, keroyokan apa kata dunia",
    "untuk kali kedua, yang sok tau gini ada sama yang udah udah jelas tak jauh beda",
    "dengan sangat berat kubilang jangan kecewa lagu mu maksudnya seram malah bikin ketawa (hahaha GOBLOK)",
    "bukan maksudku manipulasi semua salah u know the rules, di cela ya jelas balik mencari celah",
    "bertahan dari serangan ya pakai manuver  makanya kalo masih goblog semangatnya jangan over",
    "nila jangan bikin rusak susu dalam belanga jangan bawa daerah, bacotmu asal menganga",
    "sejauh ini palembang hiphop masih respect cuma dirimu yang ngamuk, coba kembali di cek",
    "kalo ngerep tuh yang bagus, nafasnya diatur, pengucapan dan lain sebagainya tuh jangan asal ehh,, gini loh 8ball *%#**#@&!%!*",
    "itu bukan ngerep man, iyu ngawur namanya ya tolol, goblok, pake otak anjing", 
]


RRAID = [
    "siapa, yang mengaku raja, tunjukkan kau punya muka",
    "magnum isi peluru rima, siap hantam kau punya nyawa",
    "tak terlihat mata, namun terdengar ditelinga, meracuni kau punya kepala, robek kau punya sendi lidah, microphonemu kubuat PATAH",
    "terbit dari timur, tinggi tak terjamah, menjulang tinggi bagai gunung HIMALAYA, kubuat kau tenggelam dibarat, terkubur jauh didalam menyentuh gelapnya bawah tanah",
    "Aku goliath selatan, kau tak suka mari buktikan",
    "i'm the FASTEST GUN IN THE SOUTH, Skema perang 65 70 langsung kujalankan",
    "(BANG BANG BANG) rasakan tembakan ini menembus kau punya tinggi hati",
    "teknik tak terdeteksi, sulit dimengerti bagai kitab suci",
    "aku original, dengan sentuhan magic harmoni",
    "aku bagai horus bersembunyi mengawasi bagai mata ILLUMINATI",
    "Silahkan hargai kepalaku karena dirimu takkan mampu, panggil pasukanmu serang aku lancarkan diseluruh penjuru",
    "pakailah amunisimu, bidiklah tiap langkahku",
    "kusiap INJAK julukanmu, sampai jumpa di arena panas bersamaku",
    "tanpa senapan di pinggang usir singa yang singgah",
    "sekarang mereka segan dahulu pandang rendah",
    "tanpa senapan di pinggang usir singa yang singgah",
    "aku melaju kencang saat target kupasang",
    "we goin BANG...BANG ",
    "(you better watchout coz now we BANG..BANG)",
    "(laughin so loud on my way to the BANK..BANK)",
    "(you better watchout coz now we BANG..BANG)",
    "Sisir kota orang maca ada rambut",
    "bangun istana diatas lapak lapuk",
    "ada yang sambit ada yang hendak sambut",
    "mereka tak dipuncak tapi kalang kabut",
    "diincar timah panas karena tim aku panas",
    "aku senyum ramah tapi rima ganas, siapa kau boy?",
    "dari selatan jakarta ke wild wild west..cowboy",
    "buka majalah aku cek horoskop, mereka bilang kubintang aku butuh teleskop",
    "aku icon baru coba cek di desktop, anak kemarin sore raja pagi besok",
    "bisnis ku handle, pernah tolak label",
    "mereka cap aku bodoh itu salah stempel",
    "kini saatku untuk unjukkan taring",
    "hustle cari laba semoga beda jaring",
    "tiap kurekaman ada PEMAKAMAN",
    "i kill wack rappers itu PEMAHAMAN",
    "nikahi permainan aku ikrar di altar",
    "bahkan kendrick? HANYA LAMAR",
    "musuh komentar, nyalakan api, kepala dingin TANPA ES DI TOPI",
    "aku diam mereka senang rumpi, lirikku peluru mereka PASANG ROMPI",
    "pada ketinggian kita rasa takut, diatas ada banyak penghasut",
    "dekati kita dengan lain maksud, karena para parasit butuhkan parasut",
    "angka angka tidak buatku angku, realita buat jatuh dari bangku",
    "sekarang hanya ada dua pilihanmu, lari dariku atau LARI DENGANKU",
    "kubangkitkan neraka karena akulah rajanya",
    "trap this, and trap that, kubuat mereka terjebak",
    "tak perlu sertifikasi diri, cukuplah karya sebagai bukti",
    "persetan mereka berkata 'SELATAN TANPA SKILL' kini kuunjuk gigi",
    "Musikku DOWNTEMPO, ku tak takut dengan HIGH TEMPO",
    "lirikku bukan BRONX, kau bilang terbelakang tapi bukan NDESO",
    "kujaga sebutan KEEP IT TRILL, lirik bening aku KEEP IT REAL",
    "Naikkan bendera keujung langit untuk kau sembah sebut aku KING OF KILL",
    "Silahkan menjiplak gayaku, karena kau takut akulah di kasta nomor SATU",
    "teruslah menyebut kecepatanmu itu dapat menumbangkan mahkota berkilau dikepalaku",
    "bila mampu, kejar TOP SPEED ku dengan mesin andalanmu",
    "Shut me down..cobalah SEBELUM SENJA menjemputmu",
    "Call me BIG VICTORY, all i do is win, represent RUN BDG",
    "bangin in the east, bangin in the west",
    "Street to club, we the BEST",
    "you left behind, we first place",
    "they to slow cuz i'm movin FAST",
    "lagi lagi si haus perhatian minta balasan jalan pintas ngetop dengan cari cari alasan",
    "bau menyengat ketenaran sedang di incar maksa ngejar mirip si konak yang lagi butuh pacar",
    "lest zi black versus 8 ball profsesional bagai bandingkan bebek sawah melawan donal",
    "gapapa, ku bantu kau terkenal sekarang jarang jarang ku baik pada lawan yang menyerang",
    "perang tak berparang tak pula bersangkur kau cuma bulu ketek yang ilang sekali dicukur",
    "omelan mirip dengkur pas tidur gak nyadar face to face battle on d stage baby, so pasti modar",
    "diss mentoknya fisik biar bodohmu tertutupi perutku makin gendut asupan gizi tercukupi",
    "ngerap masih rapi gak berantakan lagi  you inget kalo kalah titit di potong ojo melayu",
    "saat nanti ku menang, jangan kau sembunyi ingat titit dipotong, jangan kau lari",
    "bermain aman dari jauh mulutmu berak jaminan mutu dari dekat pasti jaga jarak",
    "perlu di garis bawahi lirik mu bilang 'semua' Gue solo mc, keroyokan apa kata dunia",
    "untuk kali kedua, yang sok tau gini ada sama yang udah udah jelas tak jauh beda",
    "dengan sangat berat kubilang jangan kecewa lagu mu maksudnya seram malah bikin ketawa (hahaha GOBLOK)",
    "bukan maksudku manipulasi semua salah u know the rules, di cela ya jelas balik mencari celah",
    "bertahan dari serangan ya pakai manuver  makanya kalo masih goblog semangatnya jangan over",
    "nila jangan bikin rusak susu dalam belanga jangan bawa daerah, bacotmu asal menganga",
    "sejauh ini palembang hiphop masih respect cuma dirimu yang ngamuk, coba kembali di cek",
    "kalo ngerep tuh yang bagus, nafasnya diatur, pengucapan dan lain sebagainya tuh jangan asal ehh,, gini loh 8ball *%#**#@&!%!*",
    "itu bukan ngerep man, iyu ngawur namanya ya tolol, goblok, pake otak anjing", 
]


RABSEN = [
    "Hadir bosskuh! 😀",
    "Hadir dev! 😃",
    "Hadir ngab! 😄",
    "Hadir kak!😁 ",
    "Hadir broh! 😆",
    "Hadir guru! 😂",
    "Hadir mastah! 🤣",
    "Hadir suhu! ☺️",
    "Hadir brader 😊",
    "Hadir brada 😇",
    "Hadir man! 😉",
    "Hadir master! 🤩",
    "Hadir kawan! 😎",
    "Hadir capt! 🥳",
    "Hadir sir! 🤓",
    "Hadir ndan! 😅",
    "Hadir bray! 😎",
    "Hadir cuy! 😁",
    "Hadir pro! 🔥",
    "Hadir sob! 🧐",
    "Hadir juragan! 🥳",
    "Hadir lur! 😄",
    "Hadir masbro! 👻",
    "Hadir bestie! 🧸",
    "Hadir Paman! 🙈",
    "Hadir jendral! 👮🏻‍♀️",
    "Hadir Producer! 👩🏻‍💻",
    "Hadir Metalhead! 🤘",
    "Hadir paman! 🤣",
    "Hadir dude! 🥳",
    "Hadir mahomie! 🏄🏻",
    "Hadir otw nih! 🚴🏼‍♂️"
]
